### PR TITLE
[PA]: Add loop and dominator dumping to gcc plugin

### PR DESCRIPTION
**Pull request by rsulli55**
- Loop info for each function is dumped including loop number, loop body, superloops, and children
- For each basic block, dump its loopFather, the basic blocks which dominator it, as well as the nearest common dominator of its parents

### CODE REVIEW

**Review by jobagy — APPROVED** [review]
Reviewed with Ryan and subsequently took out the special case for loops with multiple latches. 

Looks good.

**Review by jobagy — APPROVED** [review]
Looks good.

**Review by jobagy — DISMISSED** [review]
Looks good.

**Review by titomeister — APPROVED** [review]
Changes look good to me! Approved.

**Review by jobagy — APPROVED** [review]
Reviewed the changes. Looks good.

**Pull request merged**
