### PR TITLE
Overlapping description fix

### PR DESCRIPTION
**Pull request by maxaalexeeva**
- fixed a bug in untangle conj (attachments should not be empty - that was not the case when those were originally written)
- deleted unused code
- added attachments tests

### CODE REVIEW

**Comment by maxaalexeeva** [comment]
It's fine that this branch fails---it's still that foundBy bug. Should be safe to merge.

**Comment by alicekwak** [comment]
Thanks for the explanation! I'll merge this branch right now :)

**Comment by alicekwak** [comment]
@maxaalexeeva Can I delete this branch now?

**Comment by maxaalexeeva** [comment]
You can!

**Pull request merged**
