### PR TITLE
Reading from different comment formats + rule adjustments

### PR DESCRIPTION
**Pull request by maxaalexeeva**
plus whatever else the commit messages say.

Some tests broke, but I think the output overall is better. Will look at the broken tests later (ignored for now).

@pauldhein, let me know if this works for you now.

### CODE REVIEW

**Comment by maxaalexeeva** [comment]
@BeckySharp, pretty sure. Let's wait for an okay from @pauldhein before merging?

**Comment by pauldhein** [comment]
Just finished testing this in the ModX web-app. We are now seeing full link hypotheses in the PETASCE GrFN! I am still seeing high-quality link hypotheses for the SIR model, so it definitely works and is ready to be merged.

**Comment by maxaalexeeva** [comment]
@pauldhein, thanks! Gonna merge.

**Comment by BeckySharp** [comment]
thanks masha and paul!!

**Pull request merged**
