### PR TITLE
Switching to ttk widgets in pdfalign

### PR DESCRIPTION
**Pull request by adarshp**
This PR implements updates to pdfalign so that it uses ttk widgets for a more native look and feel.

### CODE REVIEW

**Comment by BeckySharp** [comment]
Since we added the <Tab> for toggling between the modes (eqn, in-text, etc) can we make these ttk buttons show the "active" or last-clicked highlight based on the current mode?
see here:
image

**Comment by adarshp** [comment]
How about radio buttons?

image

**Comment by BeckySharp** [comment]
I pulled the latest and it's not seeming to work for me anymore?
is it for you?

**Comment by BeckySharp** [comment]
but we'll figure it out and we really appreciate your help!

**Comment by adarshp** [comment]
Sorry about that @BeckySharp - apparently doing this:

```python
from tkinter import *
```

is not enough to get `filedialog` and `messagebox` - I had to put the following line back in:

```python
from tkinter import filedialog, messagebox
```

**Comment by BeckySharp** [comment]
It still isn't displaying correctly for me -- the boxes aren't highlighting
when I click them, and when I save the "snippet" is empty... are you using
it on a mac or linux? I ask bc tkinter has been flaky on mac a lot, behaves
very diff between the platforms

**Comment by adarshp** [comment]
I'm using a Mac...ok I will test it more thoroughly and get back to you.

**Comment by adarshp** [comment]
image

Seems to be working?

**Comment by BeckySharp** [comment]
Ok -- yes, seems to be working now for me, but I have 2 probs:
1) the bar goes off my screen (too much stuff, if we're doing radio
buttons, we can remove the text variable with the "currently annotating"
stuff to save space
2) the tab keystroke doesn't work anymore to switch to the next mode:
https://github.com/ml4ai/automates/blob/pdfalign_modifications_ap/pdfalign/pdfalign.py#L733-L735

I think this functionality will speed things up a bunch so do you know how
to re-enable it?

**Comment by adarshp** [comment]
The tab keystroke doesn't work in the master branch version either though...

**Comment by adarshp** [comment]
I've added some new keyboard shortcuts:

- `e` - equation mode
- `t` - text mode
- `d` - description
- `u` - unit
- `s` - save annotation

They might work to speed up the annotation as well, if the Tab keystroke doesn't end up working.

**Comment by BeckySharp** [comment]
haha, yes, you're right, when I swapped a variable I added a bug and broke the functionality, I'll check if the fix fixes it in the other branch too

**Comment by BeckySharp** [comment]
it's back working, i'll merge! thanks!!

**Comment by maxaalexeeva** [comment]
Thank you both, @adarshp  and @BeckySharp , for these updates! Very cool!

**Pull request merged**
